editAreaLoader.lang["uk"]={
new_document: "новий пустий документ",
search_button: "пошук та заміна",
search_command: "шукати слідуючий / відкрити панель пошуку",
search: "пошук",
replace: "заміна",
replace_command: "замінити / відкрити панель пошуку",
find_next: "знайти слідуюче",
replace_all: "замінити все",
reg_exp: "регулярний вираз",
match_case: "враховувати регістр",
not_found: "не знайдено.",
occurrence_replaced: "входження замінено.",
search_field_empty: "Поле пошуку пусте",
restart_search_at_begin: "Досягнуто конець документу. Починаю з початку.",
move_popup: "перемістіть вікно пошуку",
font_size: "--Розмір шрифту--",
go_to_line: "перейт до строки",
go_to_line_prompt: "перейти до строки номер:",
undo: "відмінити",
redo: "повернути",
change_smooth_selection: "ввімкнути/вимкунти деякі функції перегляду (красивіше, але використовє процесор)",
highlight: "перемкнути підсвітку синтаксису ввімкнена/вимкнена",
reset_highlight: "відновити підсвітку (якщо розсинхронизовано від тексту)",
word_wrap: "toggle word wrapping mode",
help: "про програму",
save: "зберегти",
load: "завантажити",
line_abbr: "Стр",
char_abbr: "Стлб",
position: "Позицфя",
total: "Всього",
close_popup: "закрити вспливаюче вікно",
shortcuts: "Гарячі клавіші",
add_tab: "добавити табуляцію в текст",
remove_tab: "прибрати табуляцію з текста",
about_notice: "Увага: функція подсвітки синтаксису тільки для невеликих текстів",
toggle: "Перемкнути редактор",
accesskey: "Гаряча клавіша",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Обробка...",
fullscreen: "повний екран",
syntax_selection: "--Синтаксис--",
close_tab: "Закрити файл"
};
